config/routes.rb
Rails.application.routes.draw do

  resources :images

  root 'home#new'

  post 'search', to: 'searches#show'

  get 'images/:id/download', to: 'images#download'
  get 'images/:id/download_png', to: 'images#download_png'

end

app/models/image.rb
class Image < ActiveRecord::Base
  VALID_KINDS = ['icon', 'illustration']

  has_attached_file :image
  do_not_validate_attachment_file_type :image

  acts_as_taggable

  validates :name, :image, :tag_list, presence: true
  validates :kind, inclusion: { in: VALID_KINDS }

  before_save :downcase_tags

  def downcase_tags
    self.tag_list.each { |tag| tag.downcase! }
  end
end

app/models/search.rb
class Search
  attr_reader :query
  def initialize(query, kinds)
    @query = query
    @keywords = query.split(' ').map { |word| word.strip}
    @kinds = Image::VALID_KINDS.select { |kind| kinds[kind] }
    @kinds = Image::VALID_KINDS if @kinds.empty?
  end

  def find_images
    if @keywords.empty?
      Image.all.select { |image| @kinds.include? image.kind }
    else
      Image.tagged_with(@keywords, :wild => true, :any => true)
        .select { |image| @kinds.include? image.kind }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'
  def new
  end

  def search_again
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :download, :download_png]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    data = open(@image.image.url)

    send_data data.read,
              filename: "#{@image.name}.svg",
              type: 'image/svg'
  end

  # ideally this should just use imagemagick, but nothing was working, so
  # using command line tools
  def download_png
    png_data = `curl #{@image.image.url} | rsvg-convert -h 500 -w 500 -f png`

    send_data png_data,
              filename: "#{@image.name}.png",
              type: 'image/png'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image, :name, :kind, :tag_list)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ActionController::Base
  layout 'application'
  def show
    @search = Search.new(params['search-field'], params)
    @results = @search.find_images

    if @results.empty?
      render 'home/search_again'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/new.html.erb
<div id="search-box"><h1>SEARCH GRAPHICS</h1>
  <%= form_tag("/search", method: "post") do %>
    <%= text_field_tag('search-field', params['search-field']) %><br>
    <ul>
      <li>
        <%= check_box_tag(:icon, '1', checked: 'checked') %>
        <%= label_tag(:icon, 'Icons') %>
      </li>

      <li>
        <%= check_box_tag(:illustration) %>
        <%= label_tag(:illustration, 'Illustrations') %>
      </li>
    </ul>
  <% end %>
</div>

app/views/images/_form.html.erb
<%= form_for(@image, multipart: true) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :kind %><br>
    <%= f.select :kind, ['icon', 'illustration']%>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit 'add this image' %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Tags</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image.kind %></td>
        <td><%= image.tag_list %></td>
        <td><%= image.image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div id="container">
  <h1><%= @image.name %></h1>
  <div id="result"><%= image_tag(@image.image.url, size:"500x500") %></div>
  <section id="downloadsection">
    <nav class="cl-effect-15">
      <%= link_to 'PNG', {controller: 'images', action: 'download_png'}, {'data-hover' => 'PNG'} %>
      <%= link_to 'SVG', {controller: 'images', action: 'download'}, {'data-hover' => 'SVG'} %>
    </nav>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lookout Noun Project</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="logo-header"><img src="http://i.imgur.com/4ZjtpwK.png" alt="lookout-logo"></div>

<%= yield %>

</body>
</html>

app/views/searches/show.html.erb
<div id="container">
  <h1><%= "SEARCH RESULTS FOR '#{@search.query}' " %></h1>
  <% @search.find_images.each do |image| %>
    <div class="box">
      <%= link_to image_tag(image.image.url, size:"200x200"), image_path(image) %>
    </div>
  <% end %>
</div>